micronaut:
  application:
    name: micronaut-person
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**

jackson:
  bean-introspection-module: true        

datasources:
    default:
        url: $db_url
        username: $db_user
        password: '$db_password'
        driverClassName: $db_driver

jpa:
  default:
    properties:
      hibernate:
        bytecode:
          provider: none
        hbm2ddl:
          auto: none
        show_sql: false
        
graphql:
  enabled: true 
  path: /graphql
  graphiql:
    enabled: true
    path: /graphiql