# Reference: https://github.com/marketplace/actions/aws-lambda-deploy 

name: Deploy AWS Lambda Custom Runtime with Docker Build

on:
  push:
    branches: [ graal-data-jpa ]
  pull_request:
    branches: [ graal-data-jpa ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Replace DB Configurations
      uses: datamonsters/replace-action@v2
      with:
        files: 'src/main/resources/application.yml'
        replacements: '$db_url=${{ secrets.DB_URL }},$db_user=${{ secrets.DB_USER }},$db_password=${{ secrets.DB_PASSWORD }},$db_driver=${{ secrets.DB_DRIVER }}'
    - name: Grant execute permission for deploy.sh
      run: chmod +x deploy.sh
    - name: Run deploy.sh
      run: ./deploy.sh
    - name: Deploy to AWS Lambda
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
        AWS_DEFAULT_OUTPUT: json
      run: aws lambda update-function-code --function-name micronaut-person-graal --zip-file fileb://build/function.zip
